import type { Metadata } from 'next';
import ThemeRegistry from './theme/ThemeRegistry';
import Navbar from './navbar/page';

//const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
